[workspace]
members = [
    "apps/backend_api",
    "apps/web_leptos",
    "packages/shared_core"
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
log = "0.4"
