services:
  - type: web
    name: techub-comms
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 3039
      - key: BASE_URL
        value: https://techub-comms.onrender.com
      - key: FRONTEND_URL
        value: https://techub-comms.onrender.com
      - key: API_URL
        value: https://techub-comms.onrender.com
      - key: DATABASE_URL
        value: postgresql://techub_communications_app_user:vyuCmWOhx1KuyG6PshbsoAFRXFEduKKQ@dpg-d8lpuureo5us7387vtag-a.oregon-postgres.render.com/techub_communications_app
      - key: AGORA_APP_ID
        value: "41200037042"
      - key: AGORA_APP_KEY
        value: "41200037042#200051503"
      - key: AGORA_ORG_NAME
        value: "41200037042"
      - key: AGORA_APP_NAME
        value: "200051503"
      - key: AGORA_REST_API
        value: "a41.chat.agora.io"
      - key: AGORA_CHAT_APP_TOKEN
        value: "007eJxTYHi6yGWlUAv/30fTS5Zv/7D+ySPn7btm1zG/Sl26wW3umx9mCgyJhmmGqUkWxoaJKeYmqYnJSammaQaJxqmG5kap5kmJad+8dLIaAhkZ5MPEGBgZWIGYiQHEZ2AAALyxIVU="
      - key: AGORA_CHAT_USER_TOKEN
        value: "007eJxTYDC+ojchac21HLMzenZCAhU9n+dpyKrIepZG6pvNk+lzvaDAkGiYZpiaZGFsmJhibpKamJyUappmkGicamhulGqelJj23ksnqyGQkWFxqC0LIwMrAyMQgvgqDBYpKSYmqSkGumZmFpa6hkBzdBOTLE10U5LSjMxNjc1Mk5JMAGfVJPw="
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: AGORA_SIP_AUTH_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
